//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 02:36:37 PM EDT 
//


package ontrac4j.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RateQuote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateQuote">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Service" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="FuelCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TotalCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TransitDays" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="GlobalRate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateQuote", propOrder = {
    "service",
    "serviceCharge",
    "fuelCharge",
    "totalCharge",
    "transitDays",
    "globalRate"
})
public class RateQuote {

    @XmlElement(name = "Service", required = true)
    protected String service;
    @XmlElement(name = "ServiceCharge")
    protected double serviceCharge;
    @XmlElement(name = "FuelCharge")
    protected double fuelCharge;
    @XmlElement(name = "TotalCharge")
    protected double totalCharge;
    @XmlElement(name = "TransitDays")
    protected int transitDays;
    @XmlElement(name = "GlobalRate")
    protected double globalRate;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the serviceCharge property.
     * 
     */
    public double getServiceCharge() {
        return serviceCharge;
    }

    /**
     * Sets the value of the serviceCharge property.
     * 
     */
    public void setServiceCharge(double value) {
        this.serviceCharge = value;
    }

    /**
     * Gets the value of the fuelCharge property.
     * 
     */
    public double getFuelCharge() {
        return fuelCharge;
    }

    /**
     * Sets the value of the fuelCharge property.
     * 
     */
    public void setFuelCharge(double value) {
        this.fuelCharge = value;
    }

    /**
     * Gets the value of the totalCharge property.
     * 
     */
    public double getTotalCharge() {
        return totalCharge;
    }

    /**
     * Sets the value of the totalCharge property.
     * 
     */
    public void setTotalCharge(double value) {
        this.totalCharge = value;
    }

    /**
     * Gets the value of the transitDays property.
     * 
     */
    public int getTransitDays() {
        return transitDays;
    }

    /**
     * Sets the value of the transitDays property.
     * 
     */
    public void setTransitDays(int value) {
        this.transitDays = value;
    }

    /**
     * Gets the value of the globalRate property.
     * 
     */
    public double getGlobalRate() {
        return globalRate;
    }

    /**
     * Sets the value of the globalRate property.
     * 
     */
    public void setGlobalRate(double value) {
        this.globalRate = value;
    }

}
