//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 02:36:37 PM EDT 
//


package ontrac4j.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RateShipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateShipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Rates" type="{}ArrayOfRateQuote"/>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Delzip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PUZip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Declared" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Residential" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="COD" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="SaturdayDel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="DIM" type="{}Dim"/>
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateShipment", propOrder = {
    "rates",
    "uid",
    "delzip",
    "puZip",
    "declared",
    "residential",
    "cod",
    "saturdayDel",
    "weight",
    "dim",
    "error"
})
public class RateShipment {

    @XmlElement(name = "Rates", required = true)
    protected ArrayOfRateQuote rates;
    @XmlElement(name = "UID", required = true)
    protected String uid;
    @XmlElement(name = "Delzip", required = true)
    protected String delzip;
    @XmlElement(name = "PUZip", required = true)
    protected String puZip;
    @XmlElement(name = "Declared")
    protected double declared;
    @XmlElement(name = "Residential")
    protected boolean residential;
    @XmlElement(name = "COD")
    protected double cod;
    @XmlElement(name = "SaturdayDel")
    protected boolean saturdayDel;
    @XmlElement(name = "Weight")
    protected double weight;
    @XmlElement(name = "DIM", required = true)
    protected Dim dim;
    @XmlElement(name = "Error", required = true)
    protected String error;

    /**
     * Gets the value of the rates property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRateQuote }
     *     
     */
    public ArrayOfRateQuote getRates() {
        return rates;
    }

    /**
     * Sets the value of the rates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRateQuote }
     *     
     */
    public void setRates(ArrayOfRateQuote value) {
        this.rates = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUID(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the delzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelzip() {
        return delzip;
    }

    /**
     * Sets the value of the delzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelzip(String value) {
        this.delzip = value;
    }

    /**
     * Gets the value of the puZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUZip() {
        return puZip;
    }

    /**
     * Sets the value of the puZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUZip(String value) {
        this.puZip = value;
    }

    /**
     * Gets the value of the declared property.
     * 
     */
    public double getDeclared() {
        return declared;
    }

    /**
     * Sets the value of the declared property.
     * 
     */
    public void setDeclared(double value) {
        this.declared = value;
    }

    /**
     * Gets the value of the residential property.
     * 
     */
    public boolean isResidential() {
        return residential;
    }

    /**
     * Sets the value of the residential property.
     * 
     */
    public void setResidential(boolean value) {
        this.residential = value;
    }

    /**
     * Gets the value of the cod property.
     * 
     */
    public double getCOD() {
        return cod;
    }

    /**
     * Sets the value of the cod property.
     * 
     */
    public void setCOD(double value) {
        this.cod = value;
    }

    /**
     * Gets the value of the saturdayDel property.
     * 
     */
    public boolean isSaturdayDel() {
        return saturdayDel;
    }

    /**
     * Sets the value of the saturdayDel property.
     * 
     */
    public void setSaturdayDel(boolean value) {
        this.saturdayDel = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the dim property.
     * 
     * @return
     *     possible object is
     *     {@link Dim }
     *     
     */
    public Dim getDIM() {
        return dim;
    }

    /**
     * Sets the value of the dim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dim }
     *     
     */
    public void setDIM(Dim value) {
        this.dim = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

}
