//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 02:36:40 PM EDT 
//


package ontrac4j.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentUpdate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentUpdate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tracking" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Delivered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ServiceCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="FuelCharge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TotalChrg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Residential" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentUpdate", propOrder = {
    "tracking",
    "delivered",
    "serviceCharge",
    "fuelCharge",
    "totalChrg",
    "residential",
    "weight",
    "error"
})
public class ShipmentUpdate {

    @XmlElement(name = "Tracking", required = true)
    protected String tracking;
    @XmlElement(name = "Delivered")
    protected boolean delivered;
    @XmlElement(name = "ServiceCharge")
    protected double serviceCharge;
    @XmlElement(name = "FuelCharge")
    protected double fuelCharge;
    @XmlElement(name = "TotalChrg")
    protected double totalChrg;
    @XmlElement(name = "Residential")
    protected boolean residential;
    @XmlElement(name = "Weight")
    protected double weight;
    @XmlElement(name = "Error", required = true)
    protected String error;

    /**
     * Gets the value of the tracking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTracking() {
        return tracking;
    }

    /**
     * Sets the value of the tracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTracking(String value) {
        this.tracking = value;
    }

    /**
     * Gets the value of the delivered property.
     * 
     */
    public boolean isDelivered() {
        return delivered;
    }

    /**
     * Sets the value of the delivered property.
     * 
     */
    public void setDelivered(boolean value) {
        this.delivered = value;
    }

    /**
     * Gets the value of the serviceCharge property.
     * 
     */
    public double getServiceCharge() {
        return serviceCharge;
    }

    /**
     * Sets the value of the serviceCharge property.
     * 
     */
    public void setServiceCharge(double value) {
        this.serviceCharge = value;
    }

    /**
     * Gets the value of the fuelCharge property.
     * 
     */
    public double getFuelCharge() {
        return fuelCharge;
    }

    /**
     * Sets the value of the fuelCharge property.
     * 
     */
    public void setFuelCharge(double value) {
        this.fuelCharge = value;
    }

    /**
     * Gets the value of the totalChrg property.
     * 
     */
    public double getTotalChrg() {
        return totalChrg;
    }

    /**
     * Sets the value of the totalChrg property.
     * 
     */
    public void setTotalChrg(double value) {
        this.totalChrg = value;
    }

    /**
     * Gets the value of the residential property.
     * 
     */
    public boolean isResidential() {
        return residential;
    }

    /**
     * Sets the value of the residential property.
     * 
     */
    public void setResidential(boolean value) {
        this.residential = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

}
