//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 05:34:31 PM EDT 
//


package ontrac4j.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tracking" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TransitDays" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ServiceChrg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="FuelChrg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TotalChrg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TariffChrg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SortCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentResponse", propOrder = {
    "uid",
    "tracking",
    "error",
    "transitDays",
    "serviceChrg",
    "fuelChrg",
    "totalChrg",
    "tariffChrg",
    "label",
    "sortCode"
})
public class ShipmentResponse {

    @XmlElement(name = "UID", required = true)
    protected String uid;
    @XmlElement(name = "Tracking", required = true)
    protected String tracking;
    @XmlElement(name = "Error", required = true)
    protected String error;
    @XmlElement(name = "TransitDays")
    protected int transitDays;
    @XmlElement(name = "ServiceChrg")
    protected double serviceChrg;
    @XmlElement(name = "FuelChrg")
    protected double fuelChrg;
    @XmlElement(name = "TotalChrg")
    protected double totalChrg;
    @XmlElement(name = "TariffChrg")
    protected double tariffChrg;
    @XmlElement(name = "Label", required = true)
    protected String label;
    @XmlElement(name = "SortCode", required = true)
    protected String sortCode;

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUID(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the tracking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTracking() {
        return tracking;
    }

    /**
     * Sets the value of the tracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTracking(String value) {
        this.tracking = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the transitDays property.
     * 
     */
    public int getTransitDays() {
        return transitDays;
    }

    /**
     * Sets the value of the transitDays property.
     * 
     */
    public void setTransitDays(int value) {
        this.transitDays = value;
    }

    /**
     * Gets the value of the serviceChrg property.
     * 
     */
    public double getServiceChrg() {
        return serviceChrg;
    }

    /**
     * Sets the value of the serviceChrg property.
     * 
     */
    public void setServiceChrg(double value) {
        this.serviceChrg = value;
    }

    /**
     * Gets the value of the fuelChrg property.
     * 
     */
    public double getFuelChrg() {
        return fuelChrg;
    }

    /**
     * Sets the value of the fuelChrg property.
     * 
     */
    public void setFuelChrg(double value) {
        this.fuelChrg = value;
    }

    /**
     * Gets the value of the totalChrg property.
     * 
     */
    public double getTotalChrg() {
        return totalChrg;
    }

    /**
     * Sets the value of the totalChrg property.
     * 
     */
    public void setTotalChrg(double value) {
        this.totalChrg = value;
    }

    /**
     * Gets the value of the tariffChrg property.
     * 
     */
    public double getTariffChrg() {
        return tariffChrg;
    }

    /**
     * Sets the value of the tariffChrg property.
     * 
     */
    public void setTariffChrg(double value) {
        this.tariffChrg = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the sortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortCode() {
        return sortCode;
    }

    /**
     * Sets the value of the sortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortCode(String value) {
        this.sortCode = value;
    }

}
