//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 05:34:31 PM EDT 
//


package ontrac4j.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ontrac4j.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OnTracRateResponse_QNAME = new QName("", "OnTracRateResponse");
    private final static QName _OnTracShipmentRequest_QNAME = new QName("", "OnTracShipmentRequest");
    private final static QName _OnTracTrackingResult_QNAME = new QName("", "OnTracTrackingResult");
    private final static QName _OnTracShipmentResponse_QNAME = new QName("", "OnTracShipmentResponse");
    private final static QName _OnTracPickupRequest_QNAME = new QName("", "OnTracPickupRequest");
    private final static QName _OnTracUpdateResponse_QNAME = new QName("", "OnTracUpdateResponse");
    private final static QName _OnTracPickupResponse_QNAME = new QName("", "OnTracPickupResponse");
    private final static QName _OnTracZipResponse_QNAME = new QName("", "OnTracZipResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ontrac4j.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RateShipmentList }
     * 
     */
    public RateShipmentList createRateShipmentList() {
        return new RateShipmentList();
    }

    /**
     * Create an instance of {@link ShipmentRequestList }
     * 
     */
    public ShipmentRequestList createShipmentRequestList() {
        return new ShipmentRequestList();
    }

    /**
     * Create an instance of {@link TrackingShipmentList }
     * 
     */
    public TrackingShipmentList createTrackingShipmentList() {
        return new TrackingShipmentList();
    }

    /**
     * Create an instance of {@link ShipmentResponseList }
     * 
     */
    public ShipmentResponseList createShipmentResponseList() {
        return new ShipmentResponseList();
    }

    /**
     * Create an instance of {@link PickupRequest }
     * 
     */
    public PickupRequest createPickupRequest() {
        return new PickupRequest();
    }

    /**
     * Create an instance of {@link ShipmentUpdateList }
     * 
     */
    public ShipmentUpdateList createShipmentUpdateList() {
        return new ShipmentUpdateList();
    }

    /**
     * Create an instance of {@link PickupResponse }
     * 
     */
    public PickupResponse createPickupResponse() {
        return new PickupResponse();
    }

    /**
     * Create an instance of {@link ZipCodeList }
     * 
     */
    public ZipCodeList createZipCodeList() {
        return new ZipCodeList();
    }

    /**
     * Create an instance of {@link ArrayOfRateShipment }
     * 
     */
    public ArrayOfRateShipment createArrayOfRateShipment() {
        return new ArrayOfRateShipment();
    }

    /**
     * Create an instance of {@link ArrayOfShipmentResponse }
     * 
     */
    public ArrayOfShipmentResponse createArrayOfShipmentResponse() {
        return new ArrayOfShipmentResponse();
    }

    /**
     * Create an instance of {@link ArrayOfShipmentUpdate }
     * 
     */
    public ArrayOfShipmentUpdate createArrayOfShipmentUpdate() {
        return new ArrayOfShipmentUpdate();
    }

    /**
     * Create an instance of {@link RateQuote }
     * 
     */
    public RateQuote createRateQuote() {
        return new RateQuote();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link ArrayOfTrackingShipment }
     * 
     */
    public ArrayOfTrackingShipment createArrayOfTrackingShipment() {
        return new ArrayOfTrackingShipment();
    }

    /**
     * Create an instance of {@link Consignee }
     * 
     */
    public Consignee createConsignee() {
        return new Consignee();
    }

    /**
     * Create an instance of {@link RateShipment }
     * 
     */
    public RateShipment createRateShipment() {
        return new RateShipment();
    }

    /**
     * Create an instance of {@link Shipper }
     * 
     */
    public Shipper createShipper() {
        return new Shipper();
    }

    /**
     * Create an instance of {@link ShipmentResponse }
     * 
     */
    public ShipmentResponse createShipmentResponse() {
        return new ShipmentResponse();
    }

    /**
     * Create an instance of {@link ZipCode }
     * 
     */
    public ZipCode createZipCode() {
        return new ZipCode();
    }

    /**
     * Create an instance of {@link ArrayOfRateQuote }
     * 
     */
    public ArrayOfRateQuote createArrayOfRateQuote() {
        return new ArrayOfRateQuote();
    }

    /**
     * Create an instance of {@link Dim }
     * 
     */
    public Dim createDim() {
        return new Dim();
    }

    /**
     * Create an instance of {@link TrackingShipment }
     * 
     */
    public TrackingShipment createTrackingShipment() {
        return new TrackingShipment();
    }

    /**
     * Create an instance of {@link ShipmentUpdate }
     * 
     */
    public ShipmentUpdate createShipmentUpdate() {
        return new ShipmentUpdate();
    }

    /**
     * Create an instance of {@link ArrayOfShipmentRequest }
     * 
     */
    public ArrayOfShipmentRequest createArrayOfShipmentRequest() {
        return new ArrayOfShipmentRequest();
    }

    /**
     * Create an instance of {@link ShipmentRequest }
     * 
     */
    public ShipmentRequest createShipmentRequest() {
        return new ShipmentRequest();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link ArrayOfZipCode }
     * 
     */
    public ArrayOfZipCode createArrayOfZipCode() {
        return new ArrayOfZipCode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RateShipmentList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracRateResponse")
    public JAXBElement<RateShipmentList> createOnTracRateResponse(RateShipmentList value) {
        return new JAXBElement<RateShipmentList>(_OnTracRateResponse_QNAME, RateShipmentList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShipmentRequestList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracShipmentRequest")
    public JAXBElement<ShipmentRequestList> createOnTracShipmentRequest(ShipmentRequestList value) {
        return new JAXBElement<ShipmentRequestList>(_OnTracShipmentRequest_QNAME, ShipmentRequestList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrackingShipmentList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracTrackingResult")
    public JAXBElement<TrackingShipmentList> createOnTracTrackingResult(TrackingShipmentList value) {
        return new JAXBElement<TrackingShipmentList>(_OnTracTrackingResult_QNAME, TrackingShipmentList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShipmentResponseList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracShipmentResponse")
    public JAXBElement<ShipmentResponseList> createOnTracShipmentResponse(ShipmentResponseList value) {
        return new JAXBElement<ShipmentResponseList>(_OnTracShipmentResponse_QNAME, ShipmentResponseList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PickupRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracPickupRequest")
    public JAXBElement<PickupRequest> createOnTracPickupRequest(PickupRequest value) {
        return new JAXBElement<PickupRequest>(_OnTracPickupRequest_QNAME, PickupRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShipmentUpdateList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracUpdateResponse")
    public JAXBElement<ShipmentUpdateList> createOnTracUpdateResponse(ShipmentUpdateList value) {
        return new JAXBElement<ShipmentUpdateList>(_OnTracUpdateResponse_QNAME, ShipmentUpdateList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PickupResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracPickupResponse")
    public JAXBElement<PickupResponse> createOnTracPickupResponse(PickupResponse value) {
        return new JAXBElement<PickupResponse>(_OnTracPickupResponse_QNAME, PickupResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZipCodeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnTracZipResponse")
    public JAXBElement<ZipCodeList> createOnTracZipResponse(ZipCodeList value) {
        return new JAXBElement<ZipCodeList>(_OnTracZipResponse_QNAME, ZipCodeList.class, null, value);
    }

}
