//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 05:34:31 PM EDT 
//


package ontrac4j.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ShipmentRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shipper" type="{}Shipper"/>
 *         &lt;element name="consignee" type="{}Consignee"/>
 *         &lt;element name="Service" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SignatureRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Residential" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SaturdayDel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Declared" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="COD" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CODType" type="{}codType"/>
 *         &lt;element name="Weight">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Letter" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="BillTo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Instructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Reference2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Reference3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tracking" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIM" type="{}Dim"/>
 *         &lt;element name="LabelType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ShipEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DelEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentRequest", propOrder = {

})
public class ShipmentRequest {

    @XmlElement(name = "UID", required = true)
    protected String uid;
    @XmlElement(required = true)
    protected Shipper shipper;
    @XmlElement(required = true)
    protected Consignee consignee;
    @XmlElement(name = "Service", required = true)
    protected String service;
    @XmlElement(name = "SignatureRequired")
    protected boolean signatureRequired;
    @XmlElement(name = "Residential")
    protected boolean residential;
    @XmlElement(name = "SaturdayDel")
    protected boolean saturdayDel;
    @XmlElement(name = "Declared")
    protected double declared;
    @XmlElement(name = "COD")
    protected double cod;
    @XmlElement(name = "CODType", required = true)
    @XmlSchemaType(name = "string")
    protected CodType codType;
    @XmlElement(name = "Weight")
    protected double weight;
    @XmlElement(name = "Letter")
    protected Integer letter;
    @XmlElement(name = "BillTo")
    protected int billTo;
    @XmlElement(name = "Instructions", required = true)
    protected String instructions;
    @XmlElement(name = "Reference", required = true)
    protected String reference;
    @XmlElement(name = "Reference2", required = true)
    protected String reference2;
    @XmlElement(name = "Reference3", required = true)
    protected String reference3;
    @XmlElement(name = "Tracking", required = true)
    protected String tracking;
    @XmlElement(name = "DIM", required = true)
    protected Dim dim;
    @XmlElement(name = "LabelType")
    protected int labelType;
    @XmlElement(name = "ShipEmail", required = true)
    protected String shipEmail;
    @XmlElement(name = "DelEmail", required = true)
    protected String delEmail;
    @XmlElement(name = "ShipDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar shipDate;

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUID(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return
     *     possible object is
     *     {@link Shipper }
     *     
     */
    public Shipper getShipper() {
        return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipper }
     *     
     */
    public void setShipper(Shipper value) {
        this.shipper = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link Consignee }
     *     
     */
    public Consignee getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Consignee }
     *     
     */
    public void setConsignee(Consignee value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the signatureRequired property.
     * 
     */
    public boolean isSignatureRequired() {
        return signatureRequired;
    }

    /**
     * Sets the value of the signatureRequired property.
     * 
     */
    public void setSignatureRequired(boolean value) {
        this.signatureRequired = value;
    }

    /**
     * Gets the value of the residential property.
     * 
     */
    public boolean isResidential() {
        return residential;
    }

    /**
     * Sets the value of the residential property.
     * 
     */
    public void setResidential(boolean value) {
        this.residential = value;
    }

    /**
     * Gets the value of the saturdayDel property.
     * 
     */
    public boolean isSaturdayDel() {
        return saturdayDel;
    }

    /**
     * Sets the value of the saturdayDel property.
     * 
     */
    public void setSaturdayDel(boolean value) {
        this.saturdayDel = value;
    }

    /**
     * Gets the value of the declared property.
     * 
     */
    public double getDeclared() {
        return declared;
    }

    /**
     * Sets the value of the declared property.
     * 
     */
    public void setDeclared(double value) {
        this.declared = value;
    }

    /**
     * Gets the value of the cod property.
     * 
     */
    public double getCOD() {
        return cod;
    }

    /**
     * Sets the value of the cod property.
     * 
     */
    public void setCOD(double value) {
        this.cod = value;
    }

    /**
     * Gets the value of the codType property.
     * 
     * @return
     *     possible object is
     *     {@link CodType }
     *     
     */
    public CodType getCODType() {
        return codType;
    }

    /**
     * Sets the value of the codType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodType }
     *     
     */
    public void setCODType(CodType value) {
        this.codType = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the letter property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLetter() {
        return letter;
    }

    /**
     * Sets the value of the letter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLetter(Integer value) {
        this.letter = value;
    }

    /**
     * Gets the value of the billTo property.
     * 
     */
    public int getBillTo() {
        return billTo;
    }

    /**
     * Sets the value of the billTo property.
     * 
     */
    public void setBillTo(int value) {
        this.billTo = value;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructions(String value) {
        this.instructions = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the reference2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference2() {
        return reference2;
    }

    /**
     * Sets the value of the reference2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference2(String value) {
        this.reference2 = value;
    }

    /**
     * Gets the value of the reference3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference3() {
        return reference3;
    }

    /**
     * Sets the value of the reference3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference3(String value) {
        this.reference3 = value;
    }

    /**
     * Gets the value of the tracking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTracking() {
        return tracking;
    }

    /**
     * Sets the value of the tracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTracking(String value) {
        this.tracking = value;
    }

    /**
     * Gets the value of the dim property.
     * 
     * @return
     *     possible object is
     *     {@link Dim }
     *     
     */
    public Dim getDIM() {
        return dim;
    }

    /**
     * Sets the value of the dim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dim }
     *     
     */
    public void setDIM(Dim value) {
        this.dim = value;
    }

    /**
     * Gets the value of the labelType property.
     * 
     */
    public int getLabelType() {
        return labelType;
    }

    /**
     * Sets the value of the labelType property.
     * 
     */
    public void setLabelType(int value) {
        this.labelType = value;
    }

    /**
     * Gets the value of the shipEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipEmail() {
        return shipEmail;
    }

    /**
     * Sets the value of the shipEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipEmail(String value) {
        this.shipEmail = value;
    }

    /**
     * Gets the value of the delEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelEmail() {
        return delEmail;
    }

    /**
     * Sets the value of the delEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelEmail(String value) {
        this.delEmail = value;
    }

    /**
     * Gets the value of the shipDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShipDate() {
        return shipDate;
    }

    /**
     * Sets the value of the shipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShipDate(XMLGregorianCalendar value) {
        this.shipDate = value;
    }

}
